### ISSUE TITLE
Download links in AtomicSemanticSegmention.ipynb do not work

### ISSUE THREAD

**Issue by tommycwong** [pycroscopy/atomai#80]
The download links for the training and testing datasets in AtomicSemanticSegmention.ipynb do not work anymore. Please update the download links, thanks!

**Comment by ziatdinovmax** [comment]
I think they were stored on my ORNL dropbox, which has now been deleted. My bad. I may have a copy somewhere on Google Drive. I will look it up shortly.
@aghosh92 do you have by any chance them saved on your dropbox/gdrive/etc?

**Comment by aghosh92** [comment]
Hi Maxim,

Here is a notebook link that has the files from Drive: https://drive.google.com/file/d/1GmJcbvpIQui-dtAh2sA_lYKmOlD8cVUe/view?usp=sharing

**Comment by ziatdinovmax** [comment]
@aghosh92 - thank you!

**Comment by ziatdinovmax** [comment]
Fixed via #81
